import Head from 'next/head';
import { PersonalInformation } from '../components/personalInformation';
import { PERSONAL_INFORMATION_DATA } from '../data/personalInformationData';
import { Service } from '../components/service';
import { SectionHeader } from '../components/section-header';
import { Company } from '../components/company';
import { Testimonial } from '../components/testimonial';

const About = (): JSX.Element => {
	return (
		<div className='w-full h-full bg-slightly-black'>
			<Head>
				<title>Dipayan Sukul - About</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='py-14 mx-auto w-5/6 lg:max-w-screen-2xl lg:grid lg:grid-cols-12'>
				<section className='flex justify-between items-center text-4xl text-something-blue border-b underline_position border-dotted pb-1 mb-12 sm:col-span-12'>
					<h1>About Me.</h1>
					{/* <UserIcon className='w-12 h-12' /> */}
				</section>
				<section className='lg:col-span-8 lg:pr-4'>
					<section className='text-white mb-12'>
						<h1 className='text-lg font-bold mb-5'>
							<span>Software Developer</span>
						</h1>
						<div>
							<p className='mb-4 text-left'>
								Dolor reprehenderit aut repudiandae maiores recusandae. Consequatur dolor nisi labore commodi ipsa? Excepturi velit laboriosam at voluptatibus
								cupiditate est vel. Dolorem praesentium itaque fugiat placeat quas consequatur? Obcaecati natus rerum
							</p>
						</div>
						<div>
							<p className='mb-4 text-left'>
								Consectetur consectetur nesciunt nesciunt blanditiis amet? Quod quis unde aliquid excepturi laudantium? Illo architecto aliquam velit illo
								magnam neque perferendis sint Incidunt eius ipsa inventore labore eos velit. Minus hic magni reiciendis necessitatibus ex Quidem officia
								deleniti accusamus obcaecati dolores. Porro culpa quibusdam impedit porro praesentium excepturi. Alias ab consequatur?
							</p>
						</div>
						<div>
							<span>SIGNATURE</span>
						</div>
					</section>
				</section>
				<section className='lg:col-span-4 lg:pl-4'>
					<section className='mb-12 text-white'>
						<h1>Personal Information</h1>
						<PersonalInformation personalInfomation={PERSONAL_INFORMATION_DATA} />
						<div>
							<button className='px-4 py-2 border bg-transparent text-something-blue border-something-blue bg-animated-background-position bg-no-repeat bg-animated-liner-gradient bg-animated-initial-background-size transition-animated-background-size-color duration-500 ease-custom-ease hover:bg-animated-final-background-size hover:text-white'>
								DOWNLOAD RESUME
							</button>
						</div>
					</section>
				</section>
				<section className='pb-1 md:col-span-12'>
					<section className='flex flex-col justify-center items-center mt-16'>
						<SectionHeader sectionaheader={'Services'} />
						<section className='flex flex-col sm:flex-row'>
							<Service />
						</section>
					</section>
				</section>
				<section className='pb-1 md:col-span-12'>
					<section className='flex flex-col justify-center items-center mt-8'>
						<SectionHeader sectionaheader={'Clients'} />
						<section className='flex whitespace-nowrap overflow-x-scroll scrollbar-hide max-w-full space-x-20 cursor-grab select-none relative'>
							{/* <div className='absolute h-full w-8 bg-red-100 right-0 top-0'></div> */}
							<Company />
						</section>
					</section>
				</section>
				<section className='pb-1 md:col-span-12'>
					<section className='flex flex-col justify-center items-center mt-8'>
						<SectionHeader sectionaheader={'Testimonials'} />
						<section className='flex whitespace-nowrap overflow-x-scroll scrollbar-hide max-w-full space-x-4 cursor-grab select-none text-xl'>
							<Testimonial />
						</section>
						<div className='absolute h-full w-8 opacity-10 bg-black right-0 top-0'></div>
					</section>
				</section>
			</div>
		</div>
	);
};

export default About;
