import { UserIcon } from '@heroicons/react/outline';
import Head from 'next/head';
import { PersonalInformation } from '../components/personalInformation';
import { PERSONAL_INFORMATION_DATA } from '../data/personalInformationData';

const About = (): JSX.Element => {
	return (
		<div className='w-full h-full bg-slightly-black'>
			<Head>
				<title>Dipayan Sukul - About</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='py-14 mx-auto w-5/6 sm:max-w-screen-2xl sm:grid sm:grid-cols-12'>
				<section className='flex justify-between items-center text-4xl text-something-blue border-b underline_position border-dotted pb-1 mb-12 sm:col-span-12'>
					<h1>About Me.</h1>
					<UserIcon className='w-12 h-12' />
				</section>
				<section className='sm:col-span-8 sm:pr-4'>
					<section className='text-white mb-12'>
						<h1 className='text-lg font-bold mb-5'>
							<span>Software Developer</span>
						</h1>
						<div>
							<p className='mb-4 text-left'>
								Dolor reprehenderit aut repudiandae maiores recusandae. Consequatur dolor nisi labore commodi ipsa? Excepturi velit laboriosam at voluptatibus
								cupiditate est vel. Dolorem praesentium itaque fugiat placeat quas consequatur? Obcaecati natus rerum
							</p>
						</div>
						<div>
							<p className='mb-4 text-left'>
								Consectetur consectetur nesciunt nesciunt blanditiis amet? Quod quis unde aliquid excepturi laudantium? Illo architecto aliquam velit illo
								magnam neque perferendis sint Incidunt eius ipsa inventore labore eos velit. Minus hic magni reiciendis necessitatibus ex Quidem officia
								deleniti accusamus obcaecati dolores. Porro culpa quibusdam impedit porro praesentium excepturi. Alias ab consequatur?
							</p>
						</div>
						<div>
							<span>SIGNATURE</span>
						</div>
					</section>
				</section>
				<section className='sm:col-span-4 sm:pl-4'>
					<section className='mb-12 text-white'>
						<h1>Personal Information</h1>
						<PersonalInformation personalInfomation={PERSONAL_INFORMATION_DATA} />
					</section>
				</section>
			</div>
		</div>
	);
};

export default About;
