import Head from 'next/head';

const Blog = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>Dipayan Sukul - Blog</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			BLOG GOES HERE
		</div>
	);
};

export default Blog;
