import Head from 'next/head';

const Contact = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>Dipayan Sukul - Contact</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			CONTACT GOES HERE
		</div>
	);
};

export default Contact;
