import Head from 'next/head';
import Typewriter, { Options } from 'typewriter-effect';

const Home = (): JSX.Element => {
	const options: Partial<Options> = {
		strings: ['Software Developer', 'Web designer', 'Photographer'],
		loop: true,
		delay: 75,
		autoStart: true,
	};

	return (
		<div className='flex justify-center items-center bg-hero-image bg-cover h-full w-full'>
			<Head>
				<title>Dipayan Sukul - Developer Profile</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex justify-center items-center flex-col text-white w-full'>
				<h1 className='text-6xl text-center font-medium break-words mb-5 tracking-wide'>
					<span>DIPAYAN</span> <span className='text-something-blue'>SUKUL</span>
				</h1>
				<div className='flex flex-row text-3xl'>
					<span>I am&nbsp;</span> <Typewriter options={options} />
				</div>
			</div>
		</div>
	);
};

export default Home;
