import Head from 'next/head';

const Portfolio = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>Dipayan Sukul - Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			PORTFOLIO GOES HERE
		</div>
	);
};

export default Portfolio;
