import Head from 'next/head';

const Resume = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>Dipayan Sukul - Resume</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			RESUME GOES HERE
		</div>
	);
};

export default Resume;
